jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v1
      with:
        ref: master
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___build.yml
